### ISSUE TITLE
Upgrade AztecEditor-Android to Android 13

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/AztecEditor-Android#1035]
```[tasklist]
### Tasks
- [x] Upgrade `compileSdk` to 33 https://github.com/wordpress-mobile/AztecEditor-Android/pull/1037
- [x] Upgrade `targetSdk` to 33 #1040
- [x] Publish a new version
- [ ] ~~Bump the Aztec Editor version on [WPAndroid](https://github.com/wordpress-mobile/WordPress-Android)~~
- [ ] ~~Bump the Aztec Editor version on [Gutenberg](https://github.com/wordpress-mobile/gutenberg-mobile/) in [#5556](https://github.com/wordpress-mobile/gutenberg-mobile/issues/5556)~~
```

> **Warning**
Bumping the Aztec Editor version tasks are blocked by https://github.com/wordpress-mobile/gutenberg-mobile/issues/5556. We will update both the Aztec Editor and Mobile Gutenberg simultaneously.

**Comment by ravishanker** [comment]
Should this be part of this issue https://github.com/wordpress-mobile/gutenberg-mobile/issues/5556

**Comment by irfano** [comment]
> 

This issue is related to Gutenberg but not only to it. Aztec-Editor is also [used in WPAndroid](https://github.com/wordpress-mobile/WordPress-Android/blob/d0a130164e9e01c063f685270ddbc7b7bb67a3c3/config/gradle/included_builds.gradle#L9). 
Therefore, we need to update the AztecEditor version on all consumer projects.

**Comment by irfano** [comment]
Bumping versions on WPAndroid and gutenberg-mobile will be done with https://github.com/wordpress-mobile/gutenberg-mobile/issues/5556.
