### ISSUE TITLE
Format Toolbar Redesign: Master

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/AztecEditor-Android#365]
Implement format toolbar redesign as outlined by @iamthomasbishop.

- [x] Remove features excluded from first release ([issue](https://github.com/wordpress-mobile/AztecEditor-Android/issues/366), [pull request](https://github.com/wordpress-mobile/AztecEditor-Android/pull/372))
- [x] Update layout and order of formats ([issue](https://github.com/wordpress-mobile/AztecEditor-Android/issues/367), [pull request](https://github.com/wordpress-mobile/AztecEditor-Android/pull/374))
- [x] Update media format button ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6031), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6032))
- [x] Add list menu ([issue](https://github.com/wordpress-mobile/AztecEditor-Android/issues/368), [pull request](https://github.com/wordpress-mobile/AztecEditor-Android/pull/376))
- [x] Update heading menu icons library ([issue](https://github.com/wordpress-mobile/AztecEditor-Android/issues/369), [pull request](https://github.com/wordpress-mobile/AztecEditor-Android/pull/377))
- [x] Update heading menu icons client ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6036), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6039))
- [x] Add horizontal rule format button library ([issue](https://github.com/wordpress-mobile/AztecEditor-Android/issues/373), [pull request](https://github.com/wordpress-mobile/AztecEditor-Android/pull/384))
- [x] Add horizontal rule format button client ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6045), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6051))
- [x] Add advanced toolbar toggle library ([issue](https://github.com/wordpress-mobile/AztecEditor-Android/issues/370), [pull request](https://github.com/wordpress-mobile/AztecEditor-Android/pull/388))
- [x] Add advanced toolbar toggle client ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6075), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6093))
- [x] Update button and icon size library ([issue](https://github.com/wordpress-mobile/AztecEditor-Android/issues/386), [pull request](https://github.com/wordpress-mobile/AztecEditor-Android/pull/387))
- [x] Update button and icon size client ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6078), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6084))
- [x] Add format usage analytics library ([issue](https://github.com/wordpress-mobile/AztecEditor-Android/issues/371), [pull request](https://github.com/wordpress-mobile/AztecEditor-Android/pull/392))
- [x] Add format usage analytics client ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6085), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6126))
