### ISSUE TITLE
Implement buffered action detection for user operations

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/AztecEditor-Android#555]
### Expected
In AztecText, an event is treated as 1:1 as an user operation.

### Observed
On API 26 we have a series of events happening for a single user operation (case https://github.com/wordpress-mobile/AztecEditor-Android/issues/530) - 

Situation: write the word "hola" and position the cursor right after "ho". Now insert a space. Instead of receiving one (1) single event reflecting the space insertion, this is what happens:

1) first, the “ho” part to the left of the cursor is going to be replaced by “” (that is, it’s going to be deleted)

`11-28 09:22:32.327 2793-2793/com.example.mariozorz.myapplication D/NORMAL TEST: beforeTextChanged: "hola" start: 0 count: 2 after: 0`
`11-28 09:22:32.329 2793-2793/com.example.mariozorz.myapplication D/NORMAL TEST: onTextChanged: "la" start: 0 count: 0`
`11-28 09:22:32.332 2793-2793/com.example.mariozorz.myapplication D/NORMAL TEST: afterTextChanged: "la"`

So now we’ve been left with a “la” string alone.

 

2) second, the remains of the string (that is, to the right of the cursor as originally positioned before pressing SPACE) is deleted, leaving us with an EMPTY string altogether:

`
11-28 09:22:32.340 2793-2793/com.example.mariozorz.myapplication D/NORMAL TEST: afterTextChanged: ""
`

3) Now, the left part PLUS space is inserted. That is “ho “:

`11-28 09:22:32.343 2793-2793/com.example.mariozorz.myapplication D/NORMAL TEST: beforeTextChanged: "" start: 0 count: 0 after: 3`
`11-28 09:22:32.344 2793-2793/com.example.mariozorz.myapplication D/NORMAL TEST: onTextChanged: "ho " start: 0 count: 3`
`11-28 09:22:32.349 2793-2793/com.example.mariozorz.myapplication D/NORMAL TEST: afterTextChanged: "ho "`

4) Finally, the part to the right “la” is being appended to this new string:

`11-28 09:22:32.352 2793-2793/com.example.mariozorz.myapplication D/NORMAL TEST: beforeTextChanged: "ho " start: 3 count: 0 after: 2`
`11-28 09:22:32.353 2793-2793/com.example.mariozorz.myapplication D/NORMAL TEST: onTextChanged: "ho la" start: 3 count: 2`
`11-28 09:22:32.357 2793-2793/com.example.mariozorz.myapplication D/NORMAL TEST: afterTextChanged: "ho la"`

### ToDo
- [x]  Implement a new data class that holds a `UserOperation`, which is an event sequence 
- [x] Implement a bucket system that matches a specific platform/device model, for which a specific event sequence has been observed
- [x] Implement a "wait and see" mechanism that gathers as many events as needed for observation and compares the sequence to all of the identified (well known) sequences on the corresponding bucket. When the received event sequence matches a known sequence, perform the coded operation (for example for the case described in #530), inserts a space in the original position.

**Comment by daniloercoli** [comment]
Closed in #584
